### ISSUE TITLE
"@android:id" parsed error

### ISSUE THREAD

**Issue by drakeet** [laobie/FindViewByMe#11]
Version: 1.3.0

I used `android:id="@android:id/list"` to `RecyclerView` and got the result:

`@android:id/list = (RecyclerView) findViewById(R.id.@android:id/list);`

**Comment by laobie** [comment]
@drakeet 
Update to 1.3.1, the bug has been fixed.  👀 
Happy New Year !

**Comment by drakeet** [comment]
Great! lol
