### ISSUE TITLE
Fragments unsupported

### ISSUE THREAD

**Issue by catalin-florescu** [laobie/FindViewByMe#12]
Please add support for fragments generated to initialization in Android Studio

**Comment by MAIMIHO** [comment]
如果能记住Add"m"这个状态就好了.

**Comment by fedestyla** [comment]
https://github.com/laobie/FindViewByMe/pull/13 pull request with fragments and view support

**Comment by laobie** [comment]
@fedestyla thank for your work

**Comment by laobie** [comment]
@Cataalinn the version 1.3.5 has supported Fragments 
Thanks @fedestyla

**Comment by laobie** [comment]
@MAIMIHO 
最新 1.3.6 版本已经可以记住 m 的选择了
