### ISSUE TITLE
大佬, view.findViewById()前面有时候不需要加强转

### ISSUE THREAD

**Issue by MAIMIHO** [laobie/FindViewByMe#22]
大佬, 你好, 这个插件炒鸡好用, 在Fragment里面, 用view.findViewById()前面加了强转后Android studio会提示
Casting 'view.findViewById(R.id.text)' to 'TextView' is redundant
麻烦做一个加不加这个强转的可选项. 
多谢大佬!

**Comment by laobie** [comment]
这个是 26 才出来的，暂时还没处理 后续会补上

**Comment by laobie** [comment]
已经有一个 pr 了 等我合并完代码 我就发布一个新的版本

**Comment by laobie** [comment]
@MAIMIHO 1.3.9 已经发布，明天应该可以更新了

**Comment by MAIMIHO** [comment]
@laobie 谢谢, 已经可以用了.

**Comment by laobie** [comment]
@MAIMIHO OK，那这个 issue 关闭了哈
