### ISSUE TITLE
hello  我想提交新功能

### ISSUE THREAD

**Issue by liudao01** [laobie/FindViewByMe#30]
hello  我想提交新功能  是在master上提交么 . dev 分支上东西很乱.

**Comment by laobie** [comment]
稍等 我看看哈

**Comment by laobie** [comment]
有一个问题 插件的项目 .idea 文件夹不能忽略的，忽略了项目跑不起来的

**Comment by laobie** [comment]
@liudao01 哥们，看一下我上面提到的那个问题，重新提交一笔，我再合并下。

**Comment by liudao01** [comment]
ok  已经提交了

**Comment by laobie** [comment]
好的 我晚些时候合并下

**Comment by laobie** [comment]
@liudao01 我合并后拉代码下来，发现你那边还是改动了 .idea 文件下的文件，项目直接运行不起来，你这边方便的话重新提交一比 pr 吧，你这边提交上的改动应该只有一些 java 文件和 xml 的改动最好，.idea 文件夹下面的改动不需要提交上来的，master 分支我先 reset 回去了。

**Comment by liudao01** [comment]
嗯 我懂了  .idea的文件夹下的 需要使用你的

**Comment by laobie** [comment]
嗯嗯 麻烦重新提交一个 PR 不好意思了

**Comment by liudao01** [comment]
我提交了 麻烦试下

**Comment by laobie** [comment]
好的

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/40698038-a8a4df44-63ff-11e8-89fd-6e331fc7b785.png)
这个...

**Comment by laobie** [comment]
看了下 你应该只修改了在 xml 中使用的，这个功能先暂时不发布吧，等后面完善了再发布下

**Comment by liudao01** [comment]
不会啊 我都给加上了啊   我等下看看

**Comment by laobie** [comment]
好的

**Comment by liudao01** [comment]
![mark](http://ovji4jgcd.bkt.clouddn.com/blog/180531/B2EJ3Aa0kK.gif)
hello  我这里测试没问题 麻烦看下

**Comment by laobie** [comment]
我看看

**Comment by laobie** [comment]
我重新测试了下是可以的，等我我发布下

**Comment by laobie** [comment]
1.4.0 已经提交发布，稍等一会就可以了

**Comment by zj614android** [comment]
不错
