### ISSUE TITLE
Plugin "FindViewByMe" is incompatible

### ISSUE THREAD

**Issue by nikunjparadva** [laobie/FindViewByMe#39]
Plugin Error: Plugin "FindViewByMe" is incompatible (supported only in IntelliJ IDEA).
I got error in Android Studio 4.1.0 Please solve this as soon as possible..
I really Appreciate your Plugin. but in this update It shows is incompatible..

Please solve as soon as possible.
Thanks

**Comment by MIkeeJY** [comment]
yes  Android Studio 4.1.0 is incompatible

**Comment by nikunjparadva** [comment]
Plugin is updated to 1.4.3 
https://plugins.jetbrains.com/plugin/8261-findviewbyme/
Thanks @laobie
