### ISSUE TITLE
怎么编译插件

### ISSUE THREAD

**Issue by maoruibin** [laobie/FindViewByMe#5]
没有开发过插件，不知你是通过什么方式编译的插件，我想基于你的插件加点东西！

**Comment by laobie** [comment]
@maoruibin 
你可以看看这篇 http://blog.csdn.net/wenping1980/article/details/50543295
开发环境 idea

**Comment by longtaoge** [comment]
好人呀，我已经编译成功了

**Comment by laobie** [comment]
@longtaoge 龙套哥，你基于那个插件修改完了没？

**Comment by longtaoge** [comment]
我改完后发现，他那个根本不用改，只要把获取ID的方法中的注释打开就行了。害我搞了一天。

**Comment by laobie** [comment]
@longtaoge 作者留了一手啊😂23333
